server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: apiGateway-udemyLeandro
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      -  id: cambio-service
         uri: lb://cambioservice-udemyleandro
         predicates:
         - Path=/cambio-service/**
      -  id: book-service
         uri: lb://bookservice-udemyleandro
         predicates:
         - Path=/book-service/**
      -  id: openapi
         uri: lb://apiGateway-udemyleandro
         predicates:
         - Path=/v3/api-docs/**
         filters: 
         -  RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs