eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
spring:
  application:
    name: EUREKASERVER
  security:
   basic: 
    enabled: true #habilita autenticação basica do spring security
   user: 
    name: mscurso-eureka-user #utilizar para abrir o eureka no navegador
    password: teste