spring:
 application:
  name: msclientes

server:
 port: 0 #porta random

eureka:
 client:
  service-url:
   defaultZone: http://mscurso-eureka-user:teste@localhost:8761/eureka
 instance:
  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  prefer-ip-address: true #para resolver o problema de dns