server:
  port: 8888
spring:
  application:
    name: configServer-udemyLeandro
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ThaliaLevy/microservices-training/tree/master/configServer-udemyLeandro
          default-label: master-branch
          search-paths:
          - 'greeting-service*' 