server:
  port: 8888
spring:
  application:
    name: config-udemyLeandro
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ThaliaLevy/microservices-training
          default-label: master
          search-paths:
          - 'configServer-udemyLeandro*' 