spring:
 application:
  name: mscloudgateway
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true #habilita a descoberta dos microservices
 security: #para indicar a url de onde será gerado o token (no keycloak)
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: http://localhost:8081/realms/mscurso
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      

    