spring:
 application:
  name: mscloudgateway
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true #habilita a descoberta dos microservices
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      

    