spring:
 application:
  name: mscloudgateway
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true #habilita a descoberta dos microservices
 security: #para indicar a url de onde será gerado o token (no keycloak)
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscurso
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://mscurso-eureka-user:teste@${EUREKA_SERVER}:8761/eureka #mscurso-eureka-user:teste = user:password configurado no eureka
      

    